### ISSUE TITLE
Cochran-Mantel-Haenszel

### ISSUE THREAD

**Issue by opioiddatalab** [pzivich/Python-for-Epidemiologists#6]
Thank you @pzivich for this amazing resource. Having the Hernan/Robbins causal model code in python is super helpful... g-estimation!

I have a request... do you have a Cochran-Mantel-Haenszel script? If you get the chance, please, it would be useful to us to have in this repo. Thank you in advance!

**Comment by pzivich** [comment]
I don't have any scripts that run a Cochran-Mantel-Haenszel test currently. However, it looks like `statsmodels` has a class that implements it https://www.statsmodels.org/dev/generated/statsmodels.stats.contingency_tables.StratifiedTable.html

**Comment by opioiddatalab** [comment]
Thanks! That should do nicely. Much appreciated.
